"""Add TasaDeCambio table

Revision ID: 9ca0c2bd5c23
Revises: 
Create Date: 2024-06-30 23:39:02.595279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ca0c2bd5c23'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasa_de_cambio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tasa_oficial', sa.Float(), nullable=False),
    sa.Column('tasa_compra', sa.Float(), nullable=False),
    sa.Column('tasa_venta', sa.Float(), nullable=False),
    sa.Column('tasa_wu', sa.Float(), nullable=False),
    sa.Column('tasac_bancos', sa.Float(), nullable=False),
    sa.Column('tasav_bancos', sa.Float(), nullable=False),
    sa.Column('tasap_banpro', sa.Float(), nullable=False),
    sa.Column('tasap_lafise', sa.Float(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('agencia', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasa_de_cambio')
    # ### end Alembic commands ###
