"""Add OpWu table

Revision ID: d2409fd21ab9
Revises: 9ca0c2bd5c23
Create Date: 2024-07-01 02:43:28.206672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2409fd21ab9'
down_revision = '9ca0c2bd5c23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('op_wu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('agencia', sa.String(length=20), nullable=False),
    sa.Column('transaccion', sa.String(length=50), nullable=False),
    sa.Column('tipo_operacion', sa.String(length=50), nullable=False),
    sa.Column('montotrus', sa.Float(), nullable=False),
    sa.Column('montopus', sa.Float(), nullable=False),
    sa.Column('montotrcs', sa.Float(), nullable=False),
    sa.Column('montopcs', sa.Float(), nullable=False),
    sa.Column('montoi_1000_CS', sa.Float(), nullable=False),
    sa.Column('montoi_500_CS', sa.Float(), nullable=False),
    sa.Column('montoi_200_CS', sa.Float(), nullable=False),
    sa.Column('montoi_100_CS', sa.Float(), nullable=False),
    sa.Column('montoi_50_CS', sa.Float(), nullable=False),
    sa.Column('montoi_20_CS', sa.Float(), nullable=False),
    sa.Column('montoi_10_CS', sa.Float(), nullable=False),
    sa.Column('montoi_5_CS', sa.Float(), nullable=False),
    sa.Column('montoi_1_CS', sa.Float(), nullable=False),
    sa.Column('total_entradas_CS', sa.Float(), nullable=False),
    sa.Column('cambioi_CS', sa.Float(), nullable=False),
    sa.Column('montos_1000_CS', sa.Float(), nullable=False),
    sa.Column('montos_500_CS', sa.Float(), nullable=False),
    sa.Column('montos_200_CS', sa.Float(), nullable=False),
    sa.Column('montos_100_CS', sa.Float(), nullable=False),
    sa.Column('montos_50_CS', sa.Float(), nullable=False),
    sa.Column('montos_20_CS', sa.Float(), nullable=False),
    sa.Column('montos_10_CS', sa.Float(), nullable=False),
    sa.Column('montos_5_CS', sa.Float(), nullable=False),
    sa.Column('montos_1_CS', sa.Float(), nullable=False),
    sa.Column('total_Salidas_CS', sa.Float(), nullable=False),
    sa.Column('ajuste_CS', sa.Float(), nullable=False),
    sa.Column('montoE_100_US', sa.Float(), nullable=False),
    sa.Column('montoE_50_US', sa.Float(), nullable=False),
    sa.Column('montoE_20_US', sa.Float(), nullable=False),
    sa.Column('montoE_10_US', sa.Float(), nullable=False),
    sa.Column('montoE_5_US', sa.Float(), nullable=False),
    sa.Column('montoE_1_US', sa.Float(), nullable=False),
    sa.Column('total_entradas_US', sa.Float(), nullable=False),
    sa.Column('cambioE_US', sa.Float(), nullable=False),
    sa.Column('montoP_100_US', sa.Float(), nullable=False),
    sa.Column('montoP_50_US', sa.Float(), nullable=False),
    sa.Column('montoP_20_US', sa.Float(), nullable=False),
    sa.Column('montoP_10_US', sa.Float(), nullable=False),
    sa.Column('montoP_5_US', sa.Float(), nullable=False),
    sa.Column('montoP_1_US', sa.Float(), nullable=False),
    sa.Column('total_salidas_US', sa.Float(), nullable=False),
    sa.Column('ajuste_US', sa.Float(), nullable=False),
    sa.Column('ajuste', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('op_wu')
    # ### end Alembic commands ###
